### ISSUE TITLE
import of vcf file into Google Contacts App not working, app keeps crashing when trying to access local file system to select the vcf file

### ISSUE THREAD

**Issue by Tobzi1977** [theluke/android-car-smartbox#2]
[Device Model] ux999
[Link to the purchase site] https://de.aliexpress.com/item/1005002996407751.html
[Firmware Installed: Date and Version]  2021-09-25
[Type of Car Infotainment System]  KONA electric MY2020 widescreen
[Steps to Reproduce the Problem] 
- open the Google Contacts App
- choose Settings / Import
- choose VCF file
- see that the app crashes.

FYi, my VCF file is only with 8 contacts, so not big file., only some KB...

video with the old app:
https://t.me/c/1504952832/3813

video with the new app:
https://t.me/c/1504952832/3802

![photo_2021-11-10_12-52-50](https://user-images.githubusercontent.com/94049602/141108393-c3594d3a-c7c7-46fa-bca2-f4c1c45b1ebe.jpg)

**Comment by theluke** [comment]
I can replicate the same issue unfortunately

**Comment by Tobzi1977** [comment]
Solved / workaround by the following steps:
- uninstall Google Contacts app (the newer one)
- only use the one that was shipped with the device
- Clear cache and data inside Contacts App and Contacts Store (unhide system apps to see the latter one)
- deactivate any contact sync options you can find (in-App, in device / android settings)

Export Google Contacts on the Web and send it to you be Email
Instead of downloading the VCF file and importing it inside the COntacts App, just click it inside Google Mail and "open with" Contact App for direct import.

Works. Contacts Show up in the legacy Contacts App and in the Phone App as well.

**Comment by Tobzi1977** [comment]
I think the import finally is accepted because the Account Sync is skipped by deactivating it.
So, the device does not need to "ask" any more into which Google Account to associate the imported contactdata  from the VCF.... where it failed all the time beforehand!

**Comment by theluke** [comment]
Well done @Tobzi1977 !! We closed the first issue!!!!

**Comment by theluke** [comment]
@Tobzi1977 found the workaround

**Comment by Tobzi1977** [comment]
we need to reopen. i found the imported contacts are deleted after device reboot!
