### ISSUE TITLE
Hide Navigation Circle

### ISSUE THREAD

**Issue by ewardloi** [theluke/android-car-smartbox#9]
### [Device Model]

Carlinkit AI Box

### [Phone Model]

iPhone 12 Pro Max

### [Link to the purchase site]

https://www.carlinkit.store/products/carlinkit-4g-64g-youtube-netflix-car-android-system-smart-box-wireless-android-auto-apple-carplay-ai-box

### [Firmware Installed: Date and Version]

v10.14

### [Type of Car Infotainment System, Year, Model]

Ford Sync 3 2019

### [Steps to Reproduce the Problem]

Is there any way to disable a navigation menu circle?

**Comment by theluke** [comment]
If the navigation circle is disabled, how do you move between the apps and go back to the home screen?

**Comment by ewardloi** [comment]
I'm installing a third-party app to gesture navigation control. My favorite is “Full Screen Gestures“ it works perfectly

**Comment by theluke** [comment]
Ok I will ask tomorrow the seller when he is back online

**Comment by khalilha** [comment]
@ewardloi the app above requires accessibility services. On my end at each reboot this is reset to off, isn’t it the case for you? I also have the carlinkit ai box. Thanks!

**Comment by theluke** [comment]
> @ewardloi the app above requires accessibility services. On my end at each reboot this is reset to off, isn’t it the case for you? I also have the carlinkit ai box. Thanks!

https://forum.xda-developers.com/t/accessibility-services-keep-resetting.3830548/

**Comment by khalilha** [comment]
@theluke  appreciate the support, but the solution above to my knowledge at least can’t be used with carlinkit no? I don’t see the lock option when opening recent apps.

browsing the head unit XDA forum, I see several post with the same issue for UX999.

**Comment by theluke** [comment]
Thank you for your reply, I understand your point. Maybe someone finds a solution on Xda and we can stick it here?
I wish I could do more

**Comment by khalilha** [comment]
@theluke @ewardloi as i am going crazy a little with this and lack of support from vendor, just want to double check with you (as we have the same carlinkit) if you go in accessibility services, turn one of the services ON (example for the app shared above), and reboot the device you are still having the service ON or it's reset to OFF?

**Comment by theluke** [comment]
I am going to test this tomorrow. It's bed time now here 😊

**Comment by ewardloi** [comment]
I use tasker to enable it each time after restart

**Comment by khalilha** [comment]
@ewardloi would you mind sharing your tasker profile for this? Thanks!
